name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: msys2 {0}
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
      - uses: actions/checkout@v4

      - name: Build
        run: make PLATFORM=windows NOSDL=1 SHARED=1
        working-directory: fbdoom

      - uses: actions/upload-artifact@v4
        with:
          name: dll
          path: fbdoom/fbdoom.dll
