name: Build

on:
  push:
    branches: [ "master", "tgsa" ]
  pull_request:
    branches: [ "master", "tgsa" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: make mingw-w64-ucrt-x86_64-gcc

      - uses: actions/checkout@v4
      - name: Build
        run: make PLATFORM=windows NOSDL=1 SHARED=1
        working-directory: fbdoom

      - name: rename DLL
        run: cp fbdoom/fbdoom.dll libtgsa.dll

      - uses: actions/upload-artifact@v4
        with:
          name: dll
          path: libtgsa.dll
